---
abstract: 'parses leases from isc dhcpd leases file'
author:
  - 'Jan Henning Thorsen, C<< <jhthorsen-at-cpan-org> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-DHCPd-Lease
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  POE::Filter: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
